branch-defaults:
  dev:
    environment: library-dev
  master:
    environment: library-prod
environment-defaults:
  Hiark-env:
    branch: null
    repository: null
global:
  application_name: library
  default_ec2_keyname: null
  default_platform: arn:aws:elasticbeanstalk:eu-central-1::platform/Docker running
    on 64bit Amazon Linux/2.12.4
  default_region: eu-central-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
